stages:
    - build
    - test

build-sim:
    stage: build
    image: registry.gitlab.mats.sh/mats/fpga-ci-image:latest
    script:
        - make sim

testbenches:
    stage: test
    image: registry.gitlab.mats.sh/mats/fpga-ci-image:latest
    script:
        - make test
