
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "../../src/chip8.v"

module Chip8(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		     [1:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// EPCS //////////
	output		          		EPCS_ASDO,
	input 		          		EPCS_DATA0,
	output		          		EPCS_DCLK,
	output		          		EPCS_NCSO,

	//////////// EEPROM //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// 2x13 GPIO Header //////////
	inout 		    [12:0]		GPIO_2,
	input 		     [2:0]		GPIO_2_IN,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO1,
	input 		     [1:0]		GPIO1_IN,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO2,
	input 		     [1:0]		GPIO2_IN
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [3:0] keypad_column;
wire [3:0] keypad_row;

wire [3:0] vga_r;
wire [3:0] vga_g;
wire [3:0] vga_b;
wire vga_vsync;
wire vga_hsync;

//=======================================================
//  Assignments
//=======================================================

assign GPIO2[3:0] = keypad_column;
assign keypad_row[3:2] = GPIO1_IN;
assign keypad_row[1:0] = GPIO2_IN;

assign LED[7] = GPIO1_IN[0];
assign LED[6] = GPIO1_IN[1];
assign LED[5] = GPIO2_IN[0];
assign LED[4] = GPIO2_IN[1];

// Keypad pull-up
assign GPIO2[32] = 1;

// VGA Red
assign GPIO1[1:0] = vga_r[1:0];
assign GPIO1[3] = vga_r[2];
assign GPIO1[5] = vga_r[3];
// VGA Green
assign GPIO1[9] = vga_g[0];
assign GPIO1[11] = vga_g[1];
assign GPIO1[13] = vga_g[2];
assign GPIO1[15] = vga_g[3];
// VGA Blue
assign GPIO1[17] = vga_b[0];
assign GPIO1[19] = vga_b[1];
assign GPIO1[21] = vga_b[2];
assign GPIO1[23] = vga_b[3];
// VGA Sync
assign GPIO1[31] = vga_hsync;
assign GPIO1[33] = vga_vsync;

//=======================================================
//  Structural coding
//=======================================================

chip8 chip8(.clk(CLOCK_50),
	.keypad_column(keypad_column),
	.keypad_row(keypad_row),
	.vga_r(vga_r),
	.vga_g(vga_g),
	.vga_b(vga_b),
	.vga_vsync(vga_vsync),
	.vga_hsync(vga_hsync));

endmodule
