
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "../../src/chip8.v"

module Chip8(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		     [1:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// EPCS //////////
	output		          		EPCS_ASDO,
	input 		          		EPCS_DATA0,
	output		          		EPCS_DCLK,
	output		          		EPCS_NCSO,

	//////////// EEPROM //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// 2x13 GPIO Header //////////
	inout 		    [12:0]		GPIO_2,
	input 		     [2:0]		GPIO_2_IN,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO1,
	input 		     [1:0]		GPIO1_IN,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO2,
	input 		     [1:0]		GPIO2_IN
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [3:0] keypad_column;
wire [3:0] keypad_row;

//=======================================================
//  Assignments
//=======================================================

assign GPIO2[3:0] = keypad_column;
assign keypad_row[3:2] = GPIO1_IN;
assign keypad_row[1:0] = GPIO2_IN;

//=======================================================
//  Structural coding
//=======================================================

chip8 chip8(.clk(CLOCK_50),
	.keypad_column(keypad_column),
	.keypad_row(keypad_row));

endmodule
